### ISSUE TITLE
@author Filip Procházka

### ISSUE THREAD

**Issue by fprochazka** [tacoberu/http#1]
Nějak jsi to sem zapomněl napsat ;)

https://github.com/tacoberu/http/blob/master/lib/Taco/Http/Client/HttpRequest.php#L107

**Comment by tacoberu** [comment]
Aniž bych ti chtěl upírat nějaká práva, neforkoval jsem z tvého projektu. Pokud mne paměť neklame, tak jsem to tuším vytvořil na zelené louce, a pak různě zkopírovával, co se mi zdálo dobré. A to včetně od tebe :-)
Takže nikoliv author, ale credits určitě :-) Doplním, slibuji.

**Comment by fprochazka** [comment]
Já vidím, jde to poznat :) Nejde o práva, ty vůbec neřeším, kód je opensource a tečka ;) Ale za credits budu rád :)

**Comment by tacoberu** [comment]
resolve by: f3be087819c30fe4a47b99092712ab32378f3cde

**Comment by tacoberu** [comment]
f3be087819c30fe4a47b99092712ab32378f3cde

**Comment by tacoberu** [comment]
resolve by f3be087819c30fe4a47b99092712ab32378f3cde
